/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { CovieApi } from "@fern-api/covie";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Client {
    interface Options {
        environment?: environments.CovieApiEnvironment | string;
        credentials?: core.Supplier<core.BasicAuth>;
    }
}

export class Client {
    constructor(private readonly options: Client.Options) {}

    /**
     * Lists an application's links.
     */
    public async getApplicationLinks(
        applicationId: string,
        request?: CovieApi.GetApplicationLinksRequest
    ): Promise<CovieApi.Links> {
        const _queryParams = new URLSearchParams();
        if (request?.limit != null) {
            _queryParams.append("limit", request?.limit.toString());
        }

        if (request?.offset != null) {
            _queryParams.append("offset", request?.offset.toString());
        }

        if (request?.provider != null) {
            _queryParams.append("provider", request?.provider);
        }

        if (request?.createdSince != null) {
            _queryParams.append("created_since", request?.createdSince);
        }

        if (request?.createdUntil != null) {
            _queryParams.append("created_until", request?.createdUntil);
        }

        if (request?.updatedSince != null) {
            _queryParams.append("updated_since", request?.updatedSince);
        }

        if (request?.updatedUntil != null) {
            _queryParams.append("updated_until", request?.updatedUntil);
        }

        if (request?.syncedSince != null) {
            _queryParams.append("synced_since", request?.syncedSince);
        }

        if (request?.syncedUntil != null) {
            _queryParams.append("synced_until", request?.syncedUntil);
        }

        if (request?.q != null) {
            _queryParams.append("q", request?.q);
        }

        if (request?.status != null) {
            _queryParams.append("status", request?.status);
        }

        if (request?.hasMetadata != null) {
            _queryParams.append("has_metadata", request?.hasMetadata.toString());
        }

        if (request?.policyType != null) {
            _queryParams.append("policy_type", request?.policyType);
        }

        if (request?.integrationIds != null) {
            _queryParams.append("integration_ids", request?.integrationIds);
        }

        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.CovieApiEnvironment.Production,
                `/applications/${applicationId}/links`
            ),
            method: "GET",
            headers: {
                Authorization: core.BasicAuth.toAuthorizationHeader(await core.Supplier.get(this.options.credentials)),
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.application.getApplicationLinks.Response.parse(
                _response.body as serializers.application.getApplicationLinks.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CovieApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CovieApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.CovieApiTimeoutError();
            case "unknown":
                throw new errors.CovieApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Lists an application's policies.
     */
    public async getApplicationPolicies(
        applicationId: string,
        request?: CovieApi.GetApplicationPoliciesRequest
    ): Promise<CovieApi.Policies> {
        const _queryParams = new URLSearchParams();
        if (request?.integrationIds != null) {
            _queryParams.append("integration_ids", request?.integrationIds);
        }

        if (request?.limit != null) {
            _queryParams.append("limit", request?.limit.toString());
        }

        if (request?.offset != null) {
            _queryParams.append("offset", request?.offset.toString());
        }

        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.CovieApiEnvironment.Production,
                `/applications/${applicationId}/policies`
            ),
            method: "GET",
            headers: {
                Authorization: core.BasicAuth.toAuthorizationHeader(await core.Supplier.get(this.options.credentials)),
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.application.getApplicationPolicies.Response.parse(
                _response.body as serializers.application.getApplicationPolicies.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CovieApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CovieApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.CovieApiTimeoutError();
            case "unknown":
                throw new errors.CovieApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
