/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetApplicationLinksRequest {
    /**
     * Number of results to return.
     */
    limit?: number;
    /**
     * Specifies the offset of the first result to return.
     */
    offset?: number;
    /**
     * Partial name of a provider to search against
     */
    provider?: string;
    /**
     * Limit results to links created on or after this date.
     */
    createdSince?: string;
    /**
     * Limit results to links created on or before this date.
     */
    createdUntil?: string;
    /**
     * Limit results to links last updated on or since this date.
     */
    updatedSince?: string;
    /**
     * Limit results to links last updated on or before this date.
     */
    updatedUntil?: string;
    /**
     * Limit results to links last synced on or after this date.
     */
    syncedSince?: string;
    /**
     * Limit results to links last synced on or before this date.
     */
    syncedUntil?: string;
    /**
     * Search for link via ID
     */
    q?: string;
    /**
     * Filter link status; separate multiple statuses (OR'd) with commas
     */
    status?: string;
    /**
     * Filter whether a link has metadata attached
     */
    hasMetadata?: boolean;
    /**
     * The type of policy linked.
     */
    policyType?: string;
    /**
     * If provided, only show items with any of the specified integration IDs, comma-separated.
     */
    integrationIds?: string;
}
