/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetApplicationPoliciesRequest {
    /**
     * If provided, only show items with any of the specified integration IDs, comma-separated.
     */
    integrationIds?: string;
    /**
     * Number of results to return.
     */
    limit?: number;
    /**
     * Specifies the offset of the first result to return.
     */
    offset?: number;
}
