/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListPolicyEventsRequest {
    /**
     * Number of results to return.
     */
    limit?: number;
    /**
     * Specifies the offset of the first result to return.
     */
    offset?: number;
    /**
     * Filter events by type.
     */
    eventType?: string;
}
