/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.event.rebroadcast.Response.Raw,
    CovieApi.RebroadcastEventResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).RebroadcastEventResponse);

export declare namespace Response {
    type Raw = serializers.RebroadcastEventResponse.Raw;
}
