/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The determined reason for the cancellation, such as insured_non_payment or carrier_non_renew or insured_action. This value is null when cancellation is not active or not explicitly indicated by the carrier systems and is not guaranteed to be provided in any circumstance.
 */
export type CancellationReason = "carrier_non_renew" | "insured_non_payment" | "insured_requested" | "other";

export const CancellationReason = {
    CarrierNonRenew: "carrier_non_renew",
    InsuredNonPayment: "insured_non_payment",
    InsuredRequested: "insured_requested",
    Other: "other",
} as const;
