/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A container for objects wrapped by the current object.
 */
export interface EmbeddedObjects {
    /** A list of policy fields that were unable to be processed. */
    missingFields?: string[];
}
