/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * A polymorphic list of externally linked resources related to this policy such as documents or logos for carriers.
 */
export interface LinkedResources {
    /** A list of documents obtained and available for this policy. This list may be empty if no documents are available or if document access is not enabled for your account. */
    documents?: CovieApi.DocumentRef[];
    /** A link to the logo for the carrier on the policy. */
    carrierLogo?: CovieApi.Logo;
}
