/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A string representation of the policy's current status.
 */
export type PolicyStatus = "active" | "expired" | "pending" | "cancelled";

export const PolicyStatus = {
    Active: "active",
    Expired: "expired",
    Pending: "pending",
    Cancelled: "cancelled",
} as const;
