/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

export interface Policies {
    /** Total number of results that can be returned. */
    count?: number;
    /** The total number of policies that match the filter. */
    filteredCount?: number;
    embedded?: CovieApi.EmbeddedPolicies;
}
