/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * This describes, in high level, the insurance policy record that is provided by a link. This object encapsulates all the necessary details to understand the policy's status, policyholders, and covered persons or properties.
 */
export interface Policy {
    /** Unique identifier of a policy record within the application that obtained it. */
    id?: string;
    /** String representing the object’s type. Objects of the same type share the same value. */
    object?: string;
    /** A universally-unique identifier of a policy. */
    fingerprint?: string;
    carrier?: CovieApi.Carrier;
    /** The full policy number as provided by the issuing company. This is not available to all users and may be null when not active on the account. */
    number?: string;
    /** This is a masked version of the policy number provided by the issuing company. This is always provided and available to all customers. */
    maskedNumber?: string;
    /** A string indicating the line of business this policy encompasses. */
    line?: CovieApi.LineOfBusiness;
    /** A list of insureds, or policyholders assigned to this policy. */
    policyholders?: CovieApi.Policyholder[];
    vehicles?: CovieApi.Vehicle[];
    locations?: CovieApi.Location[];
    /** A string representation of the policy's current status. */
    status?: CovieApi.PolicyStatus;
    termLength?: CovieApi.PeriodValue;
    /** The date when the policy becomes in force. This date is provided in ISO-8601 format excluding time. */
    inceptionDate?: string;
    /** The date when the described policy period ends. This date is provided in ISO-8601 format excluding time. */
    expirationDate?: string;
    /** The date when the policy is set to be cancelled. This date is provided in ISO-8601 format excluding time. */
    cancellationDate?: string;
    /** The determined reason for the cancellation, such as insured_non_payment or carrier_non_renew or insured_action. This value is null when cancellation is not active or not explicitly indicated by the carrier systems and is not guaranteed to be provided in any circumstance. */
    cancellationReason?: CovieApi.CancellationReason;
    /** The date and time which the policy was initially retrieved. This date and time is provided in ISO-8601 format. */
    linkedAt?: string;
    /** The date and time when the policy record was last updated. This date and time is provided in ISO-8601 format. */
    lastSyncedAt?: string;
    /** A polymorphic list of externally linked resources related to this policy such as documents or logos for carriers. */
    links?: CovieApi.LinkedResources;
    /** A container for objects wrapped by the current object. */
    embedded?: CovieApi.EmbeddedObjects;
    /** Unique identifier of the link associated to the policy. */
    linkId?: string;
}
