/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class CovieApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, CovieApiTimeoutError.prototype);
    }
}
