/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const LineOfBusiness: core.serialization.Schema<serializers.LineOfBusiness.Raw, CovieApi.LineOfBusiness> =
    core.serialization.enum_(["personal_auto", "homeowner", "renter", "motorcycle"]);

export declare namespace LineOfBusiness {
    type Raw = "personal_auto" | "homeowner" | "renter" | "motorcycle";
}
