/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const LinkedResources: core.serialization.ObjectSchema<
    serializers.LinkedResources.Raw,
    CovieApi.LinkedResources
> = core.serialization.object({
    documents: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).DocumentRef))
        .optional(),
    carrierLogo: core.serialization.property(
        "carrier_logo",
        core.serialization.lazyObject(async () => (await import("../../..")).Logo).optional()
    ),
});

export declare namespace LinkedResources {
    interface Raw {
        documents?: serializers.DocumentRef.Raw[] | null;
        carrier_logo?: serializers.Logo.Raw | null;
    }
}
