/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const PolicyStatus: core.serialization.Schema<serializers.PolicyStatus.Raw, CovieApi.PolicyStatus> =
    core.serialization.enum_(["active", "expired", "pending", "cancelled"]);

export declare namespace PolicyStatus {
    type Raw = "active" | "expired" | "pending" | "cancelled";
}
