/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

export interface EmbeddedRebroadcastEvents {
    /** List of broadcasts, one per endpoint called */
    broadcasts?: CovieApi.EventBroadcast[];
}
