/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Record of a broadcast to a webhook endpoint when an event is triggered.
 */
export interface EventBroadcast {
    /** Unique identifier for the broadcast. */
    id?: string;
    /** Date/Time the broadcast was prepared for delivery. */
    queuedAt?: string;
    /** Date/Time the broadcast was sent. */
    broadcastAt?: string;
    /** URI the broadcast was sent to. */
    requestUri?: string;
    /** Response code from the URI. */
    responseCode?: number;
    /** Contents of the response. */
    responseBody?: string;
}
