/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

export interface RebroadcastEventResponse {
    /** Number of endpoints called by this re-broadcast */
    count?: number;
    embedded?: CovieApi.EmbeddedRebroadcastEvents;
}
