/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const AccountWithConfig: core.serialization.ObjectSchema<
    serializers.AccountWithConfig.Raw,
    CovieApi.AccountWithConfig
> = core.serialization.object({});

export declare namespace AccountWithConfig {
    interface Raw {}
}
