/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.policy.getPoliciesPolicyId.Response.Raw, CovieApi.Policy> =
    core.serialization.lazyObject(async () => (await import("../../..")).Policy);

export declare namespace Response {
    type Raw = serializers.Policy.Raw;
}
