/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A basic object describing the individual insurance company which has issued a policy.
 */
export interface Carrier {
    /** The name of the issuing company. */
    name?: string;
}
