/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * Describes the features of a specific coverage element for a person or property, encapsulating the limits, deductibles, and premium information therein.
 */
export interface Coverage {
    /** The name of the coverage element being described. This is a coded value offered as a convenience method to avoid the need to introspect code to understand which branch of logic is being evaluated. */
    name?: string;
    /** A breakout of different limits and sublimits that apply to this coverage item. When the limits property is null, then the coverage described is selected but limits are not applicable for the coverage feature. The ommission of any limit scope indicates that it does not apply to the coverage. */
    limits?: CovieApi.CoverageLimits;
}
