/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * A breakout of different limits and sublimits that apply to this coverage item. When the limits property is null, then the coverage described is selected but limits are not applicable for the coverage feature. The ommission of any limit scope indicates that it does not apply to the coverage.
 */
export interface CoverageLimits {
    duration?: CovieApi.PeriodValue;
    term?: CovieApi.CurrencyValue;
}
