/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * Describes a value that is tied to a monetary amount. Most frequently used to describe limits, premiums, and deductibles.
 */
export interface CurrencyValue {
    /** The ISO-compatible currency code of the value being represented. */
    unit?: CovieApi.CurrencyCode;
    /** The amount of currency */
    value?: number;
}
