/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The ISO-compatible currency code of the value being represented.
 */
export type CurrencyCode = "USD" | "USD_cents";

export const CurrencyCode = {
    Usd: "USD",
    UsdCents: "USD_cents",
} as const;
