/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * Describes a discount which a policyholder is receiving for a particular covered property under a policy. When available, this object also describes the amount of savings.
 */
export interface Discount {
    /** The programming-friendly value to indicate the discount being applied. NOTE: We regularly add values to this enumeration, so your code should be able to gracefully handle unexpected enum values (though new values are documented here as they go live). */
    code?: CovieApi.DiscountType;
    /** A human-readable, friendly name for the discount. */
    friendlyName?: string;
}
