/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The programming-friendly value to indicate the discount being applied. NOTE: We regularly add values to this enumeration, so your code should be able to gracefully handle unexpected enum values (though new values are documented here as they go live).
 */
export type DiscountType =
    | "safe_driver"
    | "telematics"
    | "online"
    | "bundle"
    | "teen_driver"
    | "claim_free"
    | "homeowner"
    | "new_car"
    | "multi_car"
    | "pay_in_full"
    | "paperless_billing"
    | "loyalty"
    | "good_student"
    | "distant_student"
    | "accident_free"
    | "continuous_insurance"
    | "eft"
    | "early_quote"
    | "alarm_system"
    | "new_home"
    | "new_roof"
    | "safe_vehicle"
    | "smart_vehicle"
    | "membership"
    | "payment_plan"
    | "military"
    | "garage_parking"
    | "senior"
    | "autopay"
    | "insurance_to_value"
    | "verified_mileage"
    | "payment_history"
    | "motorcycle_endorsement";

export const DiscountType = {
    SafeDriver: "safe_driver",
    Telematics: "telematics",
    Online: "online",
    Bundle: "bundle",
    TeenDriver: "teen_driver",
    ClaimFree: "claim_free",
    Homeowner: "homeowner",
    NewCar: "new_car",
    MultiCar: "multi_car",
    PayInFull: "pay_in_full",
    PaperlessBilling: "paperless_billing",
    Loyalty: "loyalty",
    GoodStudent: "good_student",
    DistantStudent: "distant_student",
    AccidentFree: "accident_free",
    ContinuousInsurance: "continuous_insurance",
    Eft: "eft",
    EarlyQuote: "early_quote",
    AlarmSystem: "alarm_system",
    NewHome: "new_home",
    NewRoof: "new_roof",
    SafeVehicle: "safe_vehicle",
    SmartVehicle: "smart_vehicle",
    Membership: "membership",
    PaymentPlan: "payment_plan",
    Military: "military",
    GarageParking: "garage_parking",
    Senior: "senior",
    Autopay: "autopay",
    InsuranceToValue: "insurance_to_value",
    VerifiedMileage: "verified_mileage",
    PaymentHistory: "payment_history",
    MotorcycleEndorsement: "motorcycle_endorsement",
} as const;
