/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The distance unit of the value being represented.
 */
export type DistanceUnit = "mile" | "kilometer";

export const DistanceUnit = {
    Mile: "mile",
    Kilometer: "kilometer",
} as const;
