/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * Describes a value that is tied to a physical length or distance. Most frequently used to describe limits on coverages.
 */
export interface DistanceValue {
    /** The distance unit of the value being represented. */
    unit?: CovieApi.DistanceUnit;
    /** The amount of the distance in the units specified */
    value?: number;
}
