/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of document provided at the corresponding URL.
 */
export type DocumentType = "declaration" | "id_card" | "renewal" | "evidence_of_insurance" | "cancellation";

export const DocumentType = {
    Declaration: "declaration",
    IdCard: "id_card",
    Renewal: "renewal",
    EvidenceOfInsurance: "evidence_of_insurance",
    Cancellation: "cancellation",
} as const;
