/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * Describes the individual insurance document available for download from a given insurance policy, including the content-type (or mimetype) of the document.
 */
export interface DocumentRef {
    /** The type of document provided at the corresponding URL. */
    type?: CovieApi.DocumentType;
    /** The content-type, or mimetype, of the document being conveyed at this location. */
    contentType?: string;
    /** The path to retrieve the document described in this object. */
    href?: string;
}
