/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * Describes the individual driver who is considered the routine operator of the vehicle it is attached to and who is explicitly included under the coverage terms selected for the vehicle.
 */
export interface Driver {
    name?: CovieApi.Name;
    /** The date of birth of the driver, when provided by the insurer. Represented as an ISO-8601 date. */
    dateOfBirth?: string;
    /** The current marital status of the driver, if provided. The `separated` value includes divorced status. */
    maritalStatus?: CovieApi.MaritalStatus;
    /** The reported gender of the driver, when provided by the insurer. */
    gender?: CovieApi.Gender;
    /** The age in which the driver was first licensed, when provided by the insurer. */
    ageLicensed?: number;
    /** The drivers license number of the driver when provided by the insurer. This value may be masked. */
    licenseNumber?: string;
    /** The state in which the driver is licensed. Represented in abbreviated form. */
    licenseState?: string;
    /** A flag indicating if the driver is described as the primary driver of the vehicle. When no clear indication is made by an insurer, the first listed driver is assumed to be the primary. */
    isPrimary?: boolean;
}
