/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A universal base object encapsulating the e-mail address related to another object.
 */
export interface EMail {
    address?: string;
    isPrimary?: boolean;
}
