/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumerated string representing the type of event that occurred.
 */
export type EventType =
    | "link.created"
    | "link.successful"
    | "link.documents.available"
    | "link.broken"
    | "link.stale"
    | "link.changed"
    | "policies.unlinked"
    | "policy.activated"
    | "policy.cancelling"
    | "policy.expired"
    | "policy.reinstated"
    | "policy.renewed"
    | "policy.changed"
    | "policy.changed.coverage"
    | "policy.changed.insureds"
    | "policy.changed.status"
    | "policy.changed.premium";

export const EventType = {
    LinkCreated: "link.created",
    LinkSuccessful: "link.successful",
    LinkDocumentsAvailable: "link.documents.available",
    LinkBroken: "link.broken",
    LinkStale: "link.stale",
    LinkChanged: "link.changed",
    PoliciesUnlinked: "policies.unlinked",
    PolicyActivated: "policy.activated",
    PolicyCancelling: "policy.cancelling",
    PolicyExpired: "policy.expired",
    PolicyReinstated: "policy.reinstated",
    PolicyRenewed: "policy.renewed",
    PolicyChanged: "policy.changed",
    PolicyChangedCoverage: "policy.changed.coverage",
    PolicyChangedInsureds: "policy.changed.insureds",
    PolicyChangedStatus: "policy.changed.status",
    PolicyChangedPremium: "policy.changed.premium",
} as const;
