/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

export interface EventPayloadLinkContainer {
    /** Link to view the full event payload. */
    payload?: CovieApi.EventPayloadLink;
}
