/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

export interface Events {
    /** The total, unfiltered number of events without pagination */
    count?: number;
    /** The unpaginated number of events matching the filter */
    filteredCount?: number;
    embedded?: CovieApi.EmbeddedEvents;
}
