/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The reported gender of the driver, when provided by the insurer.
 */
export type Gender = "male" | "female" | "non-binary";

export const Gender = {
    Male: "male",
    Female: "female",
    NonBinary: "non-binary",
} as const;
