/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An indication if the insured is a business or individual.
 */
export type InsuredType = "person" | "business";

export const InsuredType = {
    Person: "person",
    Business: "business",
} as const;
