/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * Describes an entity, person or company, that has a legal interest in a piece of covered property. This could represent a bank or other financial institution who owns a loan/mortgage/lien over a covered property, a landlord who owns the property a tenant is leasing, or some other recognized stakeholder who is entitled to certain information rights from the insurance company regarding the covered property.
 */
export interface Interest {
    /** The type of interest being described. Such as: lender, landlord, guarantor, or other. */
    type?: CovieApi.InterestType;
    name?: CovieApi.Name;
    /** E-Mail addresses used to contact the interested party. */
    emailAddresses?: CovieApi.EMail[];
    /** Phone Numbers used to call the interested party. Provided in E164 format. */
    phoneNumbers?: CovieApi.Phone[];
}
