/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of interest being described. Such as: lender, landlord, guarantor, or other.
 */
export type InterestType = "landlord" | "lender" | "guarantor" | "other";

export const InterestType = {
    Landlord: "landlord",
    Lender: "lender",
    Guarantor: "guarantor",
    Other: "other",
} as const;
