/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A string representation of the link's current status. This is distinct from a policy's status which is an indicator to whether a policy is in force. A link's status is an indicator of how new and complete the data is and whether or not it is possible to retrieve refreshed information.
 */
export type LinkStatus = "new" | "active" | "document_uploaded" | "broken" | "revoked" | "stale";

export const LinkStatus = {
    New: "new",
    Active: "active",
    DocumentUploaded: "document_uploaded",
    Broken: "broken",
    Revoked: "revoked",
    Stale: "stale",
} as const;
