/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

export interface Links {
    /** Total number of results that can be returned. */
    count?: number;
    /** If a search filter is applied, this will return the total number of results that match the filter. */
    filteredCount?: number;
    embedded?: CovieApi.EmbeddedLinks;
}
