/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * Describes a physical location and/or structure which is covered under the terms of an insurance policy.
 */
export interface Location {
    address?: CovieApi.Address;
    /** A list of coverages that apply to the location being insured. */
    coverages?: CovieApi.CoverageInfo;
    /** A list of deductibles that apply in addition to the coverage-specific deductibles. */
    otherDeductibles?: unknown;
    /** A list of discounts being applied to the location. */
    discounts?: CovieApi.Discount[];
    /** A list of interested parties, such as mortgagers, lienholders, guarantors, landlords, or others. */
    interests?: CovieApi.Interest[];
}
