/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The current marital status of the driver, if provided. The `separated` value includes divorced status.
 */
export type MaritalStatus = "married" | "single" | "separated" | "widowed";

export const MaritalStatus = {
    Married: "married",
    Single: "single",
    Separated: "separated",
    Widowed: "widowed",
} as const;
