/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * Describes a value that is represented as a percentage, fraction, or ratio of another value. Most frequently depicted for deductibles which may be a percentage of a limit.
 */
export interface PercentageValue {
    /** Always "percentage" */
    unit?: CovieApi.Percentage;
    /** The percentage amount determined by this value. */
    value?: number;
}
