/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Always "percentage"
 */
export type Percentage = "percentage";

export const Percentage = {
    Percentage: "percentage",
} as const;
