/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * Describes a value that represents a period of time, such as days, weeks, or months.
 */
export interface PeriodValue {
    /** The scale of time period being represented. */
    unit?: CovieApi.TimeScale;
    /** The amount of time being represented. */
    value?: number;
}
