/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PhoneType = "mobile" | "home" | "office" | "fax";

export const PhoneType = {
    Mobile: "mobile",
    Home: "home",
    Office: "office",
    Fax: "fax",
} as const;
