/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * Describes the company or person which is legally listed on, and entitled to benefits from the policy for which they are attached.
 */
export interface Policyholder {
    /** An indication if the insured is a business or individual. */
    type?: CovieApi.InsuredType;
    name?: CovieApi.Name;
    /** The contact e-mail addresses of the insured, if known. */
    emailAddresses?: CovieApi.EMail[];
    /** The contact phone numbers of the insured, if known. */
    phoneNumbers?: CovieApi.Phone[];
    /** A flag indicating if the insured is explicitly referenced as primary, or assumed primary as being the first insured listed on the policy. */
    isPrimary?: boolean;
}
