/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * Describes a value that is relative to another, such as the fair market value or replacement value. It is inherently variable and subject to the context in which it is invoked.
 */
export interface RelativeValue {
    /** Always "other". */
    unit?: CovieApi.Other;
    /** The form of measure used to calculate the relative value, such as "actual cash value" or "ACV" which looks at the original price or investment and factors in depreciation (effectively "Fair Market Value"), or "replacement cost" (sometimes "Actual Loss Sustained" or "ALS") which sets a value against real cost to replace something today. Occasionally, a response of "unknown" may be returned. This value indicates that no specific value was provided in high level policy documents. The value may be subjective and specific to the individual policyholder as specified in their policy contract and should be manually reviewed. */
    value?: CovieApi.ActualCashValue;
}
