/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The scale of time period being represented.
 */
export type TimeScale = "day" | "week" | "month";

export const TimeScale = {
    Day: "day",
    Week: "week",
    Month: "month",
} as const;
