/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovieApi } from "@fern-api/covie";

/**
 * Describes the motor vehicle which is covered under the terms of a policy. This object contains details of the specific coverages provided for this vehicle and information about the drivers who are covered.
 */
export interface Vehicle {
    /** The unique Vehicle Identification Number (VIN) that pertains to this vehicle. */
    vin?: string;
    /** The manufacturer of the vehicle covered by this policy. */
    make?: string;
    /** The model of the vehicle covered by this policy. */
    model?: string;
    /** The 4-digit model year of the vehicle covered by this policy. */
    year?: string;
    /** The trim of the vehicle covered by this policy. */
    trim?: string;
    /** The series of the vehicle covered by this policy. */
    series?: string;
    /** When provided, the estimated number of miles this vehicle is expected to be driven, per year. When a range is specified by the carrier, the highest value in the range is provided. */
    annualMileage?: number;
    /** The intended usage of the vehicle by the insured. */
    usage?: CovieApi.VehicalUsage;
    /** Whether or not the vehicle specified is owned, leased, or financed by the insured. */
    ownership?: CovieApi.VehicleOwnership;
    /** A list of drivers assigned to this vehicle. */
    drivers?: CovieApi.Driver[];
    /** The financial institution which presently holds a lien against the vehicle. */
    interests?: CovieApi.Interest[];
    /** A list of all coverages that apply to this vehicle. The omission of any coverage indicates that coverage was either declined or does not apply to this vehicle. */
    coverages?: CovieApi.VehicleCoverage;
    /** A list of discounts being applied to the premium of this vehicle. */
    discounts?: CovieApi.Discount[];
}
