/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The intended usage of the vehicle by the insured.
 */
export type VehicalUsage = "commute" | "pleasure" | "business";

export const VehicalUsage = {
    Commute: "commute",
    Pleasure: "pleasure",
    Business: "business",
} as const;
