/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether or not the vehicle specified is owned, leased, or financed by the insured.
 */
export type VehicleOwnership = "own" | "lease" | "finance";

export const VehicleOwnership = {
    Own: "own",
    Lease: "lease",
    Finance: "finance",
} as const;
