/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.account.enableAccountMfaRequired.Response.Raw,
    CovieApi.AccountWithConfig
> = core.serialization.lazyObject(async () => (await import("../../..")).AccountWithConfig);

export declare namespace Response {
    type Raw = serializers.AccountWithConfig.Raw;
}
