/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const CovieApiEnvironment = {
    Production: "https://api.covie.io/v1",
    Mock: "https://stoplight.io/mocks/covie/link-access/37161102",
} as const;

export type CovieApiEnvironment = typeof CovieApiEnvironment.Production | typeof CovieApiEnvironment.Mock;
