/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.application.getApplicationLinks.Response.Raw,
    CovieApi.Links
> = core.serialization.lazyObject(async () => (await import("../../..")).Links);

export declare namespace Response {
    type Raw = serializers.Links.Raw;
}
