/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.application.getApplicationPolicies.Response.Raw,
    CovieApi.Policies
> = core.serialization.lazyObject(async () => (await import("../../..")).Policies);

export declare namespace Response {
    type Raw = serializers.Policies.Raw;
}
