/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const ActualCashValue: core.serialization.Schema<serializers.ActualCashValue.Raw, CovieApi.ActualCashValue> =
    core.serialization.enum_(["actual_cash_value", "replacement_value", "unknown"]);

export declare namespace ActualCashValue {
    type Raw = "actual_cash_value" | "replacement_value" | "unknown";
}
