/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const CurrencyCode: core.serialization.Schema<serializers.CurrencyCode.Raw, CovieApi.CurrencyCode> =
    core.serialization.enum_(["USD", "USD_cents"]);

export declare namespace CurrencyCode {
    type Raw = "USD" | "USD_cents";
}
