/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const CurrencyValue: core.serialization.ObjectSchema<serializers.CurrencyValue.Raw, CovieApi.CurrencyValue> =
    core.serialization.object({
        unit: core.serialization.lazy(async () => (await import("../../..")).CurrencyCode).optional(),
        value: core.serialization.number().optional(),
    });

export declare namespace CurrencyValue {
    interface Raw {
        unit?: serializers.CurrencyCode.Raw | null;
        value?: number | null;
    }
}
