/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const DiscountType: core.serialization.Schema<serializers.DiscountType.Raw, CovieApi.DiscountType> =
    core.serialization.enum_([
        "safe_driver",
        "telematics",
        "online",
        "bundle",
        "teen_driver",
        "claim_free",
        "homeowner",
        "new_car",
        "multi_car",
        "pay_in_full",
        "paperless_billing",
        "loyalty",
        "good_student",
        "distant_student",
        "accident_free",
        "continuous_insurance",
        "eft",
        "early_quote",
        "alarm_system",
        "new_home",
        "new_roof",
        "safe_vehicle",
        "smart_vehicle",
        "membership",
        "payment_plan",
        "military",
        "garage_parking",
        "senior",
        "autopay",
        "insurance_to_value",
        "verified_mileage",
        "payment_history",
        "motorcycle_endorsement",
    ]);

export declare namespace DiscountType {
    type Raw =
        | "safe_driver"
        | "telematics"
        | "online"
        | "bundle"
        | "teen_driver"
        | "claim_free"
        | "homeowner"
        | "new_car"
        | "multi_car"
        | "pay_in_full"
        | "paperless_billing"
        | "loyalty"
        | "good_student"
        | "distant_student"
        | "accident_free"
        | "continuous_insurance"
        | "eft"
        | "early_quote"
        | "alarm_system"
        | "new_home"
        | "new_roof"
        | "safe_vehicle"
        | "smart_vehicle"
        | "membership"
        | "payment_plan"
        | "military"
        | "garage_parking"
        | "senior"
        | "autopay"
        | "insurance_to_value"
        | "verified_mileage"
        | "payment_history"
        | "motorcycle_endorsement";
}
