/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const Discount: core.serialization.ObjectSchema<serializers.Discount.Raw, CovieApi.Discount> =
    core.serialization.object({
        code: core.serialization.lazy(async () => (await import("../../..")).DiscountType).optional(),
        friendlyName: core.serialization.property("friendly_name", core.serialization.string().optional()),
    });

export declare namespace Discount {
    interface Raw {
        code?: serializers.DiscountType.Raw | null;
        friendly_name?: string | null;
    }
}
