/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const DistanceUnit: core.serialization.Schema<serializers.DistanceUnit.Raw, CovieApi.DistanceUnit> =
    core.serialization.enum_(["mile", "kilometer"]);

export declare namespace DistanceUnit {
    type Raw = "mile" | "kilometer";
}
