/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const DocumentRef: core.serialization.ObjectSchema<serializers.DocumentRef.Raw, CovieApi.DocumentRef> =
    core.serialization.object({
        type: core.serialization.lazy(async () => (await import("../../..")).DocumentType).optional(),
        contentType: core.serialization.property("content_type", core.serialization.string().optional()),
        href: core.serialization.string().optional(),
    });

export declare namespace DocumentRef {
    interface Raw {
        type?: serializers.DocumentType.Raw | null;
        content_type?: string | null;
        href?: string | null;
    }
}
