/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const DocumentType: core.serialization.Schema<serializers.DocumentType.Raw, CovieApi.DocumentType> =
    core.serialization.enum_(["declaration", "id_card", "renewal", "evidence_of_insurance", "cancellation"]);

export declare namespace DocumentType {
    type Raw = "declaration" | "id_card" | "renewal" | "evidence_of_insurance" | "cancellation";
}
