/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const EMail: core.serialization.ObjectSchema<serializers.EMail.Raw, CovieApi.EMail> = core.serialization.object({
    address: core.serialization.string().optional(),
    isPrimary: core.serialization.property("is_primary", core.serialization.boolean().optional()),
});

export declare namespace EMail {
    interface Raw {
        address?: string | null;
        is_primary?: boolean | null;
    }
}
