/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const EmbeddedLinks: core.serialization.ObjectSchema<serializers.EmbeddedLinks.Raw, CovieApi.EmbeddedLinks> =
    core.serialization.object({
        links: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).Link))
            .optional(),
    });

export declare namespace EmbeddedLinks {
    interface Raw {
        links?: serializers.Link.Raw[] | null;
    }
}
