/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const EventPayloadLinkContainer: core.serialization.ObjectSchema<
    serializers.EventPayloadLinkContainer.Raw,
    CovieApi.EventPayloadLinkContainer
> = core.serialization.object({
    payload: core.serialization.lazyObject(async () => (await import("../../..")).EventPayloadLink).optional(),
});

export declare namespace EventPayloadLinkContainer {
    interface Raw {
        payload?: serializers.EventPayloadLink.Raw | null;
    }
}
