/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const EventPayloadLink: core.serialization.ObjectSchema<
    serializers.EventPayloadLink.Raw,
    CovieApi.EventPayloadLink
> = core.serialization.object({
    href: core.serialization.string().optional(),
});

export declare namespace EventPayloadLink {
    interface Raw {
        href?: string | null;
    }
}
