/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const EventType: core.serialization.Schema<serializers.EventType.Raw, CovieApi.EventType> =
    core.serialization.enum_([
        "link.created",
        "link.successful",
        "link.documents.available",
        "link.broken",
        "link.stale",
        "link.changed",
        "policies.unlinked",
        "policy.activated",
        "policy.cancelling",
        "policy.expired",
        "policy.reinstated",
        "policy.renewed",
        "policy.changed",
        "policy.changed.coverage",
        "policy.changed.insureds",
        "policy.changed.status",
        "policy.changed.premium",
    ]);

export declare namespace EventType {
    type Raw =
        | "link.created"
        | "link.successful"
        | "link.documents.available"
        | "link.broken"
        | "link.stale"
        | "link.changed"
        | "policies.unlinked"
        | "policy.activated"
        | "policy.cancelling"
        | "policy.expired"
        | "policy.reinstated"
        | "policy.renewed"
        | "policy.changed"
        | "policy.changed.coverage"
        | "policy.changed.insureds"
        | "policy.changed.status"
        | "policy.changed.premium";
}
