/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const Gender: core.serialization.Schema<serializers.Gender.Raw, CovieApi.Gender> = core.serialization.enum_([
    "male",
    "female",
    "non-binary",
]);

export declare namespace Gender {
    type Raw = "male" | "female" | "non-binary";
}
