/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const InsuredType: core.serialization.Schema<serializers.InsuredType.Raw, CovieApi.InsuredType> =
    core.serialization.enum_(["person", "business"]);

export declare namespace InsuredType {
    type Raw = "person" | "business";
}
