/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const InterestType: core.serialization.Schema<serializers.InterestType.Raw, CovieApi.InterestType> =
    core.serialization.enum_(["landlord", "lender", "guarantor", "other"]);

export declare namespace InterestType {
    type Raw = "landlord" | "lender" | "guarantor" | "other";
}
