/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const LinkStatus: core.serialization.Schema<serializers.LinkStatus.Raw, CovieApi.LinkStatus> =
    core.serialization.enum_(["new", "active", "document_uploaded", "broken", "revoked", "stale"]);

export declare namespace LinkStatus {
    type Raw = "new" | "active" | "document_uploaded" | "broken" | "revoked" | "stale";
}
