/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const LinkDetails: core.serialization.ObjectSchema<serializers.LinkDetails.Raw, CovieApi.LinkDetails> =
    core.serialization.object({
        href: core.serialization.string().optional(),
        contentType: core.serialization.property("content_type", core.serialization.string().optional()),
    });

export declare namespace LinkDetails {
    interface Raw {
        href?: string | null;
        content_type?: string | null;
    }
}
