/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const MaritalStatus: core.serialization.Schema<serializers.MaritalStatus.Raw, CovieApi.MaritalStatus> =
    core.serialization.enum_(["married", "single", "separated", "widowed"]);

export declare namespace MaritalStatus {
    type Raw = "married" | "single" | "separated" | "widowed";
}
