/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const Other: core.serialization.Schema<serializers.Other.Raw, CovieApi.Other> = core.serialization.enum_([
    "other",
]);

export declare namespace Other {
    type Raw = "other";
}
