/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const PercentageValue: core.serialization.ObjectSchema<
    serializers.PercentageValue.Raw,
    CovieApi.PercentageValue
> = core.serialization.object({
    unit: core.serialization.lazy(async () => (await import("../../..")).Percentage).optional(),
    value: core.serialization.number().optional(),
});

export declare namespace PercentageValue {
    interface Raw {
        unit?: serializers.Percentage.Raw | null;
        value?: number | null;
    }
}
