/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const Percentage: core.serialization.Schema<serializers.Percentage.Raw, CovieApi.Percentage> =
    core.serialization.enum_(["percentage"]);

export declare namespace Percentage {
    type Raw = "percentage";
}
