/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovieApi } from "@fern-api/covie";
import * as core from "../../../../core";

export const PhoneType: core.serialization.Schema<serializers.PhoneType.Raw, CovieApi.PhoneType> =
    core.serialization.enum_(["mobile", "home", "office", "fax"]);

export declare namespace PhoneType {
    type Raw = "mobile" | "home" | "office" | "fax";
}
